name: 'match'
inputs:
  match:
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Match
      shell: bash
      run: |
        ls result.log || exit -1
        cat result.log

        result='$(cat result.log)'

        echo "A"
        ([[ "$result" =~ ($match) ]] && echo "Matched: $match") || (echo "!Matched: $match" && exit -1)
        echo "B"