name: 'match'
inputs:
  matches: # Pass a string JSON array of strings
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Match
      if: runner.os == 'Windows'
      shell: bash
      run: |
        ls result.log || exit -1
        cat result.log

        result='$(cat result.log)'
        match='${{ fromJson(inputs.match) }}'

        ([[ "$result" =~ ($match) ) ]] && echo "Matched: $match") || (echo "!Matched: $match" && exit -1)