name: 'match'
inputs:
  matches: # Pass a string JSON array of strings
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Match
      shell: bash
      run: |
        ls result.log || exit -1
        cat result.log

        result='$(cat result.log)'
        match='${{ fromJson(inputs.match) }}'
        echo "$match"

        echo "A"
        ([[ "$result" =~ ($match) ]] && echo "Matched: $match") || (echo "!Matched: $match" && exit -1)
        echo "B"