inputs:
  args:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: 'Erase Existing Output File'
      shell: bash
      run: |
        rm -f result.log
        rm -f exit_code.log
    - name: Test
      if: runner.os == 'Windows'
      shell: bash
      run: |
        set -o pipefail

        ./build/Debug/TeekValidator.exe${{ inputs.args }} 2> result.log
        echo $? | tee exit_code.log
    - name: Test
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -o pipefail

        ./build/TeekValidator${{ inputs.args }} 2> result.log
        echo $? | tee exit_code.log