inputs:
  args:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: 'Erase Existing Output File'
      shell: bash
      run: |
        rm -f result.log
    - name: Test
      if: runner.os == 'Windows'
      shell: bash
      run: |
        ./build/Debug/TeekValidator.exe${{ inputs.args }} &> result.log
    - name: Test
      if: runner.os == 'Linux'
      shell: bash
      run: |
        ./build/TeekValidator${{ inputs.args }} &> result.log