inputs:
  do_cache:
    type: boolean
    default: false
    required: false
  working_directory:
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    #- name: Key Date
    #  if: ${{ inputs.do_cache }}
    #  id: date
    #  shell: bash
    #  run: echo "date=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT
    - name: Cache Workspace
      if: ${{ inputs.do_cache }}
      id: cache-internal
      uses: actions/cache@v3
      with:
        path: |
          ./cxx/lib/TeekValidator/build
        key: |
          validator-cache-${{ runner.os }}-${{ hashFiles('./cxx/lib/TeekValidator/.git') }}

    - name: Release Build
      if: steps.cache-internal.outputs.cache-hit != 'true'
      uses: ./cxx/lib/TeekValidator/.github/workflows/build
      with:
        release: true
        working_directory: ${{ inputs.working_directory }}
