inputs:
  do_cache:
    type: boolean
    default: false
    required: false
  working_directory:
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    #- name: Key Git
    #  if: ${{ inputs.do_cache }}
    #  id: key
    #  shell: bash
    #  run: |
    #    echo "git=$(git -C ./cxx/lib/TeekValidator rev-parse HEAD)" >> $GITHUB_OUTPUT
    #- name: Cache Release Build
    #  if: ${{ inputs.do_cache }}
    #  id: cache-internal
    #  uses: actions/cache@v3
    #  with:
    #    path: |
    #      ./cxx/lib/TeekValidator/build
    #    key: |
    #      validator-cache-${{ runner.os }}-${{ steps.key.outputs.git }}

    - name: Checkout
      if: steps.cache-internal.outputs.cache-hit == 'true'
      shell: bash
      run: |
        git config --local advice.detachedHead false

        git fetch
        git checkout ${{ github.sha }} --force

    - name: Release Build
      if: steps.cache-internal.outputs.cache-hit != 'true'
      uses: ./cxx/lib/TeekValidator/.github/workflows/build
      with:
        release: true
        working_directory: ${{ inputs.working_directory }}
