inputs:
  do_cache:
    type: boolean
    default: false
    required: false
  working_directory:
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Key Date
      if: ${{ inputs.do_cache }}
      id: date
      shell: bash
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
    - name: Cache Workspace
      if: ${{ inputs.do_cache }}
      id: cache-internal
      uses: actions/cache@v3
      with:
        path: |
          ./cxx/lib/TeekValidator/build
        key: |
          validator-cache-${{ steps.date.outputs.date }}
        restore-keys: |
          validator-cache

    - name: Release Build
      uses: ./cxx/lib/TeekValidator/.github/workflows/build
      with:
        release: true
        working_directory: ${{ inputs.working_directory }}
