inputs:
  do_cache:
    type: boolean
    default: false
    required: false
defaults:
  run:
    working-directory: ./lib/cxx/TeekValidator
runs:
  using: 'composite'
  steps:
    - name: Release Build
      uses: ./lib/cxx/TeekValidator/.github/workflows/build
      with:
        release: true

    #- name: Key Date
    #  id: date
    #  shell: bash
    #  run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
    #- name: Cache Workspace
    #  id: cache-internal
    #  uses: actions/cache@v3
    #  with:
    #    path: |
    #      ${{ inputs.path }}
    #    key: |
    #      ${{ inputs.key }}-cache-${{ steps.date.outputs.date }}
    #    restore-keys: |
    #      ${{ inputs.key }}-cache
