name: 'test_fail'
inputs:
  log_file:
    required: true
    type: string
  regex_file:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Test
      uses: ./.github/workflows/test
      with:
        log_file: ${{ inputs.log_file }}
        regex_file: ${{ inputs.regex_file }}
        patternA: '[^\n]*Matches[^\n]+Failed[^\n]*'
        patternB: '[^\n]*Exclusions[^\n]+Passed[^\n]*'
    - name: Validate
      uses: ./.github/workflows/reported_failures