inputs:
  log_file:
    required: true
    type: string
  regex_file:
    required: true
    type: string
  working_directory:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Validate
      if: runner.os == 'Windows'
      shell: bash
      run: |
        ${{ inputs.working_directory }}/build/Release/TeekValidator.exe ${{ inputs.log_file }} ${{ inputs.regex_file }}
    - name: Validate
      if: runner.os == 'Linux'
      shell: bash
      run: |
        ${{ inputs.working_directory }}//build/TeekValidator ${{ inputs.log_file }} ${{ inputs.regex_file }}