inputs:
  log_file:
    required: true
    type: string
  regex_file:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - uses: ./.github/workflows/test_unvalidated_
      with:
        args: ' ${{ inputs.log_file }} ${{ inputs.regex_file }}'