runs:
  using: 'composite'
  steps:
    - uses: ./.github/workflows/test_unvalidated_
      with:
        args: ''
    - name: Exit Code
      uses: ./.github/workflows/match_exit_code_not
      with:
        undesired_code: 0