runs:
  using: 'composite'
  steps:
    - name: Validate
      uses: ./.github/workflows/match
      with:
        pattern: '[^\|]'
    - name: Exit Code
      uses: ./.github/workflows/match_exit_code
      with:
        desired_code: 0