inputs:
  log_file:
    required: true
    type: string
  regex_file:
    required: true
    type: string
  match_count:
    required: true
    type: number
  exclusion_count:
    required: true
    type: number
runs:
  using: 'composite'
  steps:
    - name: Test
      uses: ./.github/workflows/test
      with:
        log_file: ${{ inputs.log_file }}
        regex_file: ${{ inputs.regex_file }}
        patternA: '[^\n]*${{ inputs.match_count }}[^\n]+Matches[^\n]+Passed[^\n]*'
        patternB: '[^\n]*${{ inputs.exclusion_count }}[^\n]+Exclusions[^\n]+Passed[^\n]*'
    - name: Validate
      uses: ./.github/workflows/reported_no_failures