inputs:
  undesired_code:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Exit Code
      shell: bash
      run: |
        ls exit_code.log || exit -1
        cat exit_code.log

        exit_code="$(cat exit_code.log)"
        ( ! [[ "$exit_code" =~ (${{ inputs.undesired_code }}) ]] && echo "Exit Code Did Not Match: ${{ inputs.undesired_code }}") || (echo "Exit Code Matched: ${{ inputs.undesired_code }}" && exit -1)