on:
  push:
    branches:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cmake -S cxx -B build
          cmake --build build --config Release
      - name: Test
        if: runner.os == 'Windows'
        run: |
          ./build/Release/TeekValidator.exe test.log test.regex
      - name: Test
        if: runner.os == 'Linux'
        run: |
          sudo chmod +x ./build/TeekValidator
          ./build/TeekValidator test.log test.regex