on:
  push:
    branches:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cmake -S cxx -B build
          cmake --build build --config Release
      - name: pass.regex
        uses: ./.github/workflows/test_pass_no_failures
        with:
          log_file: tests/pass.log
          regex_file: tests/pass.regex
      - name: hex_pass.regex
        uses: ./.github/workflows/test_pass_no_failures
        with:
          log_file: tests/pass.log
          regex_file: tests/pass.regex