on:
  push:
    branches:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cmake -S cxx -B build
          cmake --build build --config Release
      - name: Test
        uses: ./.github/workflows/test
        with:
          log_file: tests/pass.log
          regex_file: tests/pass.regex
      - name: Cat
        shell: bash
        run: |
          ls result.log || exit -1

          result='$(cat result.log)'

          if [[ "$result" =~ ^Matches Passed$ ]]; then
            exit -1
          fi
          if [[ "$result" =~ ^Exclusions Passed$ ]]; then
            exit -1
          fi