on:
  push:
    branches:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug Build
        uses: ./.github/workflows/build
        with:
          release: false

      # See https://www.regextester.com/99203 for syntax, bash is different than modern regex
      # Even still, bash regex seems to fail in weird situations. Try till it works.

      - name: Usage
        uses: ./.github/workflows/test_blank
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'TeekValidator[^\n]+LOG[^\n]+REGEXES[^\n]+'
      - name: Exit Code
        uses: ./.github/workflows/match_exit_code_not
        with:
          undesired_code: 0

      - name: Usage
        uses: ./.github/workflows/test_unvalidated
        with:
          log_file: '1 2'
          regex_file: '3 4'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'TeekValidator[^\n]*LOG[^\n]*REGEXES[^\n]*'
      - name: Exit Code
        uses: ./.github/workflows/match_exit_code_not
        with:
          undesired_code: 0

      - name: Non-Existent Log
        uses: ./.github/workflows/test_unvalidated
        with:
          log_file: 'tests/nonexistent.log'
          regex_file: 'tests/pass.regex'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '\.log[^\n]*does not exist'
      - name: Exit Code
        uses: ./.github/workflows/match_exit_code_not
        with:
          undesired_code: 0

      - name: Non-Existent Regex
        uses: ./.github/workflows/test_unvalidated
        with:
          log_file: 'tests/pass.log'
          regex_file: 'tests/nonexistent.regex'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '\.regex[^\n]*does not exist'
      - name: Exit Code
        uses: ./.github/workflows/match_exit_code_not
        with:
          undesired_code: 0

      - name: Both Non-Existent
        uses: ./.github/workflows/test_unvalidated
        with:
          log_file: 'tests/nonexistent.log'
          regex_file: 'tests/nonexistent.regex'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '\.log[^\n]*does not exist'
      - name: Exit Code
        uses: ./.github/workflows/match_exit_code_not
        with:
          undesired_code: 0

      - name: Pass
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/pass.log
          regex_file: tests/pass.regex
          match_count: 5
          exclusion_count: 5
      - name: Pass
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/hex.log
          regex_file: tests/hex_pass.regex
          match_count: 20
          exclusion_count: 0

      - name: Pass Edge Case
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/edge_cases/only.log
          regex_file: tests/edge_cases/only_exclusions_pass.regex
          match_count: 0
          exclusion_count: 4
      - name: Pass Edge Case
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/edge_cases/only.log
          regex_file: tests/edge_cases/only_matches_pass.regex
          match_count: 5
          exclusion_count: 0

      - name: Pass EOF
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/eof/eof.log
          regex_file: tests/eof/eof.regex
          match_count: 3
          exclusion_count: 0
      - name: Pass EOF
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/eof/eof_1.log
          regex_file: tests/eof/eof_1.regex
          match_count: 4
          exclusion_count: 4
      - name: Pass EOF
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/eof/eof_2.log
          regex_file: tests/eof/eof_2.regex
          match_count: 4
          exclusion_count: 4
      - name: Pass EOF
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/eof/eof_3.log
          regex_file: tests/eof/eof_3.regex
          match_count: 4
          exclusion_count: 0
      - name: Pass EOF
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/eof/eof_4.log
          regex_file: tests/eof/eof_4.regex
          match_count: 4
          exclusion_count: 0
      - name: Pass EOF
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/eof/eof_5.log
          regex_file: tests/eof/eof_5.regex
          match_count: 4
          exclusion_count: 4
      - name: Pass EOF
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/eof/eof_6.log
          regex_file: tests/eof/eof_6.regex
          match_count: 4
          exclusion_count: 4
      - name: Pass EOF
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/eof/eof_7.log
          regex_file: tests/eof/eof_7.regex
          match_count: 4
          exclusion_count: 0
      - name: Pass EOF
        uses: ./.github/workflows/test_pass_pass
        with:
          log_file: tests/eof/eof_8.log
          regex_file: tests/eof/eof_8.regex
          match_count: 4
          exclusion_count: 0



      - name: Fail
        uses: ./.github/workflows/test_fail_fail
        with:
          log_file: tests/both_fail.log
          regex_file: tests/both_fail.regex
          match_count: 0
          exclusion_count: 0
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'Any Line[^\n\|]+\|[^\n]+\^987\$[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '4321[^\n\|]+\|[^\n]+\^4321\$[^\w]'

      - name: Fail
        uses: ./.github/workflows/test_fail_pass
        with:
          log_file: tests/match_fail.log
          regex_file: tests/match_fail.regex
          match_count: 0
          exclusion_count: 0
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'Any Line[^\n\|]+\|[^\n]+\^Random string Y\$[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'Any Line[^\n\|]+\|[^\n]+\^Random string C\$[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'Any Line[^\n\|]+\|[^\n]+\^Random string Z\$[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'Any Line[^\n\|]+\|[^\n]+\^Random string D\$[^\w]'

      - name: Fail
        uses: ./.github/workflows/test_pass_fail
        with:
          log_file: tests/exclusion_fail.log
          regex_file: tests/exclusion_fail.regex
          match_count: 0
          exclusion_count: 0
      - name: Validate
        uses: ./.github/workflows/match_not
        with:
          pattern: 'Any Line'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'There was an error, catch this line[^\n\|]+\|[^\n]+error[^\w]'

      - name: Fail
        uses: ./.github/workflows/test_fail_fail
        with:
          log_file: tests/hex.log
          regex_file: tests/hex_fail.regex
          match_count: 0
          exclusion_count: 0
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'Any Line'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+0[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+1[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+2[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+3[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+4[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+5[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+6[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+7[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+8[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+9[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+a[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+b[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+c[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+d[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+e[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '22 b5 f4 cf a0 e8 f8 c2 7e d7 12 55 59 b5 25 7f[^\n\|]+\|[^\n]+f[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '93 97 cd 76 cd fX 65 b4 75 e6 1d 57 dd dd e4 ba[^\n\|]+\|[^\n]+X[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'fa 7f e5 40 df 0a f6 33 43 84 64 cd 80 62 11 9Y[^\n\|]+\|[^\n]+Y[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'R7 ef 1b d8 b6 a1 ab 57 03 7f 82 11 99 79 e5 61[^\n\|]+\|[^\n]+R[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'fa 7f e5 40 df 0a f6 33 43 84 64 cd 80 62 11 9Y[^\n\|]+\|[^\n]+\[RY\][^\w]'


      - name: Fail Edge Case
        uses: ./.github/workflows/test_pass_fail
        with:
          log_file: tests/edge_cases/fail_last_exclusion_not_missed.log
          regex_file: tests/edge_cases/fail_last_exclusion_not_missed.regex
          match_count: 0
          exclusion_count: 4
      - name: Validate
        uses: ./.github/workflows/match_not
        with:
          pattern: 'Any Line'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'ZC[^\n\|]+\|[^\n]+C[^\w]'

      - name: Fail Edge Case
        uses: ./.github/workflows/test_pass_fail
        with:
          log_file: tests/edge_cases/only.log
          regex_file: tests/edge_cases/only_exclusions_fail.regex
          match_count: 0
          exclusion_count: 4
      - name: Validate
        uses: ./.github/workflows/match_not
        with:
          pattern: 'Any Line'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '1234[^\n\|]+\|[^\n]+1[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '1234[^\n\|]+\|[^\n]+2[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '1234[^\n\|]+\|[^\n]+3[^\w]'
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: '1234[^\n\|]+\|[^\n]+4[^\w]'

      - name: Fail Edge Case
        uses: ./.github/workflows/test_fail_pass
        with:
          log_file: tests/edge_cases/only.log
          regex_file: tests/edge_cases/only_matches_fail.regex
          match_count: 0
          exclusion_count: 4
      - name: Validate
        uses: ./.github/workflows/match
        with:
          pattern: 'Any Line[^\n\|]+\|[^\n]+12345[^\w]'